name: 'Set up Python and uv'
description: 'Sets up Python, installs uv, sets up uv cache, and creates and activates a virtual environment.'
inputs:
  python-version:
    description: "Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset. Passed to setup-python."
  cache:
    description: "Whether to cache uv's cache directory. Default is true."
    default: "true"
  cache-dependency-path:
    description: "Specify dependency files hash for cache key. Supports wildcards or a list of file names."
outputs:
  python-version:
    description: "The version of Python that was set up."
    value: ${{ steps.setup-python.outputs.python-version }}
  cache-hit:
    description: "Whether the cache was restored."
    value: ${{ steps.setup-uv-cache.outputs.cache-hit }}
  python-path:
    description: "The path to the Python executable."
    value: ${{ steps.setup-python.outputs.python-path }}
  uv-path:
    description: "The path to the uv executable."
    value: ${{ steps.install-uv.outputs.uv-path }}
runs:
  using: "composite"
  steps:
    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      id: install-uv
      shell: bash
      run: |
        pipx install uv
        echo "uv-path=$(which uv)" >> $GITHUB_OUTPUT
        echo "uv-cache-dir=$(uv cache dir)" >> $GITHUB_OUTPUT

    - name: Generate checksum of cache dependencies
      id: cache-dependency-checksum
      if: ${{ inputs.cache == 'true' && inputs.cache-dependency-path }}
      shell: bash
      run: |
        echo "checksum=$(md5sum ${{ inputs.cache-dependency-path }} | md5sum | awk '{ print $1 }')" >> $GITHUB_OUTPUT

    - name: Set up uv cache
      id: setup-uv-cache
      uses: actions/cache@v4
      if: ${{ inputs.cache == 'true' }}
      with:
        path: ${{ steps.install-uv.outputs.uv-cache-dir }}
        key: setup-python-uv-action-${{ runner.os }}-${{ steps.cache-dependency-checksum.outputs.checksum }}
        save-always: true

    - name: Create virtual environment
      shell: bash
      run: |
        uv venv $HOME/.venv

    - name: Activate virtual environment (Unix)
      if: ${{ runner.os != 'Windows' }}
      shell: bash
      run: |
        echo "$HOME/.venv/bin" >> $GITHUB_PATH
        echo "VIRTUAL_ENV=$HOME/.venv" >> $GITHUB_ENV

    - name: Activate virtual environment (Windows)
      if: ${{ runner.os == 'Windows' }}
      shell: bash
      run: |
        echo "$HOME/.venv/Scripts" >> $GITHUB_PATH
        echo "VIRTUAL_ENV=$HOME/.venv" >> $GITHUB_ENV
