name: example

on: 
  push: 
    branches: [main]

jobs:
  example-job:
    name: "Example (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python with uv
      uses: drivendataorg/setup-python-uv-action@main
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        uv pip install cowsay

    - name: Run Python code
      run: |
        python -c "import cowsay; cowsay.cow('Moo')"
