name: test

on: 
  pull_request:
  push: 
    branches: [main]
  workflow_dispatch:

jobs:
  tests-cache-packages:
    name: "Test (${{ matrix.os }}, caching: ${{ matrix.cache }})"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        cache: ["none", "packages", "venv"]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python with uv (local source)
        uses: ./
        with:
          python-version: "3.12"
          cache: ${{ matrix.cache }}
          cache-dependency-path: >-
            test_assets/requirements.txt

      - name: Check active Python
        run: |
          echo "Python: $(which python)"
          echo "Python version: $(python --version)"

      - name: Install dependencies
        run: |
          uv pip install -r test_assets/requirements.txt

      - name: Test some stuff
        run: |
          python -c "import cloudpathlib; print('cloudpathlib:', cloudpathlib.__version__)"
          nbautoexport --version
          mkdocs --version
          pytest --version

      - name: Test Makefile command
        run: |
          make test
